---

  - name: Check if OS is Ubuntu 16.04 Xenial (this playbook does not support others)
    debug: msg="Check OS"
    failed_when: ansible_distribution != "Ubuntu" and ansible_distribution_version != "16.04"

