---

  - name: 1.7.1.1 Ensure message of the day is configured properly (Scored)
    lineinfile:
      dest: /etc/motd
      create: yes
      line: 'Authorized uses only. All activity may be monitored and reported.'
      state: present
    tags:
      - section1
      - section1.7
      - section1.7.1.1

  - name: 1.7.1.2 Ensure local login warning banner is configured properly (Not Scored)
    shell: egrep '(\\v|\\r|\\m|\\s)' /etc/issue
    register: egrep_os_infos
    failed_when: egrep_os_infos.rc == 0
    changed_when: False
    tags:
      - section1
      - section1.7
      - section1.7.1.2

  - name: 1.7.1.3 Ensure remote login warning banner is configured properly (Not Scored)
    shell: egrep '(\\v|\\r|\\m|\\s)' /etc/issue.net
    register: egrep_os_infos
    failed_when: egrep_os_infos.rc == 0
    changed_when: False
    tags:
      - section1
      - section1.7
      - section1.7.1.3

  - name: 1.7.1.4 Ensure permissions on /etc/motd are configured (Not Scored)
    file:
      path: /etc/motd
      owner: root
      group: root
      mode: 0644
    tags:
      - section1
      - section1.7
      - section1.7.1.4

  - name: 1.7.1.5 Ensure permissions on /etc/issue are configured (Scored)
    file:
      path: /etc/issue
      owner: root
      group: root
      mode: 0644
    tags:
      - section1
      - section1.7
      - section1.7.1.5

  - name: 1.7.1.6 Ensure permissions on /etc/issue.net are configured (Not Scored)
    file:
      path: /etc/issue.net
      owner: root
      group: root
      mode: 0644
    tags:
      - section1
      - section1.7
      - section1.7.1.7

  - name: 1.7.2 Ensure GDM login banner is configured (Scored)
    stat:
      path: /etc/dconf/profile/gdm
    register: gdm_rule
    tags:
      - section1
      - section1.7
      - section1.7.2

  - name: 1.7.2 Ensure GDM login banner is configured (Scored)
    apt: name=dconf-cli force=yes state=installed
    when: gdm_rule.stat.exists == False
    tags:
      - section1
      - section1.7
      - section1.7.2

  - name: 1.7.2 Ensure GDM login banner is configured (Scored)
    file: path={{ item }} state=directory recurse=yes
    with_items:
      - /etc/dconf/profile/
      - /etc/dconf/db/gdm.d/
    when: gdm_rule.stat.exists == False
    tags:
      - section1
      - section1.7
      - section1.7.2

  - name: 1.7.2 Ensure GDM login banner is configured (Scored)
    lineinfile:
      dest: /etc/dconf/profile/gdm
      state: present
      create: yes
      line: '{{ item.line }}'
    with_items:
      - { line: 'user-db:user' }
      - { line: 'system-db:gdm' }
      - { line: 'file-db:/usr/share/gdm/greeter-dconf-defaults' }
    when: gdm_rule.stat.exists == False
    tags:
      - section1
      - section1.7
      - section1.7.2

  - name: 1.7.2 Ensure GDM login banner is configured (Scored)
    lineinfile:
      dest: /etc/dconf/db/gdm.d/01-banner-message
      state: present
      create: yes
      line: '{{ item.line }}'
    with_items:
      - { line: '[org/gnome/login-screen]' }
      - { line: 'banner-message-enable=true' }
      - { line: 'banner-message-text="UNAUTHORIZED ACCESS TO THIS LINUX INSTANCE IS PROHIBITED. This computer system is the property of EvidentIO. You must have explicit have permission to access or configure this device. All activities on this device may be logged. Violations of this policy may result in disciplinary action and may be reported to law enforcement.--- There is no right to privacy on this device --- WARNING - This session is being monitored by Evident.IO DevOps Team."' }
    when: gdm_rule.stat.exists == False
    notify: update dconf
    tags:
      - section1
      - section1.7
      - section1.7.2
